spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Cura
    username: ${D_USERNAME}
    password: ${D_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_index_ddl: true

  security.oauth2.client:
    registration:
      google:
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}

  redis:
    uri: ${REDIS_URI}
api.prefix: /api/v1

admin:
  init:
    email1: ${admin1}
    password1: ${password1}

auth:
  token:
    jwt: ${JWT_SECRET}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}
